# This is an example Starter pipeline configuration
# Use a skeleton to build, test and deploy using manual and parallel steps
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: cirrusci/flutter

pipelines:
  pull-requests: 
    '{develop}': 
    - step:
        services:
          - docker
        script: # Modify the commands below to build your repository.
          - flutter pub get
          - flutter --version
          - flutter analyze
