const MORE_KEY_PROFILE = '1';
const MORE_KEY_SAVE_ITEMS = '2';
const MORE_KEY_PARKING_REMINDER = '3';
const MORE_KEY_SETTINGS = '4';
const MORE_KEY_HELP = '5';
const MORE_KEY_POST_AND_REVIEW = '6';
const MORE_KEY_LOGOUT = '7';
const COMMUNITY_DETAIL_KEY_LIKED = '1';
